<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CanvasBlocksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('canvas_blocks')->delete();
        
        \DB::table('canvas_blocks')->insert(array (
            0 => 
            array (
                'id' => 3,
                'canvas_version_id' => 1,
                'block' => 'custom.leftTextSliderRight',
                'key' => '',
                'options' => '{"color": "#D65A54", "loops": {"loop": {"items": [{}, {}, {}]}}, "margin": "py-8 md:py-16 size:large", "textColor": "white", "padding_top": "pt-8 md:pt-16 top_size:large", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-8 md:pb-16 bottom_size:large", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 1,
                '_rgt' => 18,
                'parent_id' => NULL,
                'created_at' => '2023-05-04 02:32:10',
                'updated_at' => '2023-05-04 04:40:43',
            ),
            1 => 
            array (
                'id' => 4,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<h2>Nieuwe baan nodig?<br />\\nVind de perfecte match</h2>\\n\\n<p>Dit is een faketekst. Alles wat hier staat is slechts om een indruk te geven van het grafische effect van tekst op deze plek. Wat u hier leest is een voorbeeldtekst. Deze wordt later vervangen door de uiteindelijke tekst, die nu nog niet bekend is. De faketekst is dus een tekst die eigenlijk nergens over gaat. Het grappige is, dat mensen deze toch vaak lezen. Zelfs als men weet dat het om een faketekst gaat, lezen ze toch door.</p>\\n"}',
                'visible' => 1,
                '_lft' => 2,
                '_rgt' => 3,
                'parent_id' => 3,
                'created_at' => '2023-05-04 02:32:11',
                'updated_at' => '2023-05-04 02:32:11',
            ),
            2 => 
            array (
                'id' => 5,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 4,
                '_rgt' => 5,
                'parent_id' => 3,
                'created_at' => '2023-05-04 02:32:11',
                'updated_at' => '2023-05-04 02:32:11',
            ),
            3 => 
            array (
                'id' => 6,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.0.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 6,
                '_rgt' => 7,
                'parent_id' => 3,
                'created_at' => '2023-05-04 04:40:43',
                'updated_at' => '2023-05-04 04:40:43',
            ),
            4 => 
            array (
                'id' => 7,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.1.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 8,
                '_rgt' => 9,
                'parent_id' => 3,
                'created_at' => '2023-05-04 04:40:43',
                'updated_at' => '2023-05-04 04:40:43',
            ),
            5 => 
            array (
                'id' => 8,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.2.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 10,
                '_rgt' => 11,
                'parent_id' => 3,
                'created_at' => '2023-05-04 04:40:43',
                'updated_at' => '2023-05-04 04:40:43',
            ),
            6 => 
            array (
                'id' => 9,
                'canvas_version_id' => 1,
                'block' => 'custom.vacancySlider',
                'key' => '',
                'options' => '{"color": "#D65A54", "loops": {"loop": {"items": [{}, {}, {}, {}, {}]}}, "margin": "py-8 md:py-16 size:large", "padding_top": "pt-8 md:pt-16 top_size:large", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-8 md:pb-16 bottom_size:large", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 19,
                '_rgt' => 36,
                'parent_id' => NULL,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 11:45:49',
            ),
            7 => 
            array (
                'id' => 10,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"text": "Vacatures"}',
                'visible' => 1,
                '_lft' => 20,
                '_rgt' => 21,
                'parent_id' => 9,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 07:42:03',
            ),
            8 => 
            array (
                'id' => 11,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.button',
                'key' => 'button',
                'options' => '{"text": "Bekijk alle vacatures", "target": "_self", "linkTarget": "websitePage", "websitePageId": 4, "disableButtonText": "aan"}',
                'visible' => 1,
                '_lft' => 22,
                '_rgt' => 23,
                'parent_id' => 9,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 07:42:03',
            ),
            9 => 
            array (
                'id' => 12,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.0.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 24,
                '_rgt' => 25,
                'parent_id' => 9,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 07:42:03',
            ),
            10 => 
            array (
                'id' => 13,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.1.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 26,
                '_rgt' => 27,
                'parent_id' => 9,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 07:42:03',
            ),
            11 => 
            array (
                'id' => 14,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.2.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 28,
                '_rgt' => 29,
                'parent_id' => 9,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 07:42:03',
            ),
            12 => 
            array (
                'id' => 15,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.3.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 30,
                '_rgt' => 31,
                'parent_id' => 9,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 07:42:03',
            ),
            13 => 
            array (
                'id' => 16,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.4.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 32,
                '_rgt' => 33,
                'parent_id' => 9,
                'created_at' => '2023-05-05 07:42:03',
                'updated_at' => '2023-05-05 07:42:03',
            ),
            14 => 
            array (
                'id' => 18,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.line',
                'key' => 'line',
                'options' => '{"text": "Vacatures"}',
                'visible' => 1,
                '_lft' => 34,
                '_rgt' => 35,
                'parent_id' => 9,
                'created_at' => '2023-05-05 11:45:49',
                'updated_at' => '2023-05-05 11:45:49',
            ),
            15 => 
            array (
                'id' => 19,
                'canvas_version_id' => 1,
                'block' => 'custom.sponsorSlider',
                'key' => '',
                'options' => '{"loops": {"loop": {"items": [{}, {}, {}, {}, {}, {}, {}]}}}',
                'visible' => 1,
                '_lft' => 37,
                '_rgt' => 54,
                'parent_id' => NULL,
                'created_at' => '2023-05-05 15:17:50',
                'updated_at' => '2023-05-05 15:17:50',
            ),
            16 => 
            array (
                'id' => 20,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.line',
                'key' => 'line',
                'options' => '{"text": "Onze opdrachtgevers"}',
                'visible' => 1,
                '_lft' => 38,
                '_rgt' => 39,
                'parent_id' => 19,
                'created_at' => '2023-05-05 15:17:50',
                'updated_at' => '2023-05-05 15:17:50',
            ),
            17 => 
            array (
                'id' => 21,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.0.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 40,
                '_rgt' => 41,
                'parent_id' => 19,
                'created_at' => '2023-05-05 15:17:50',
                'updated_at' => '2023-05-05 15:17:50',
            ),
            18 => 
            array (
                'id' => 22,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.3.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 42,
                '_rgt' => 43,
                'parent_id' => 19,
                'created_at' => '2023-05-05 15:17:50',
                'updated_at' => '2023-05-05 15:17:50',
            ),
            19 => 
            array (
                'id' => 23,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.2.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 44,
                '_rgt' => 45,
                'parent_id' => 19,
                'created_at' => '2023-05-05 15:17:50',
                'updated_at' => '2023-05-05 15:17:50',
            ),
            20 => 
            array (
                'id' => 24,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.1.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 46,
                '_rgt' => 47,
                'parent_id' => 19,
                'created_at' => '2023-05-05 15:17:50',
                'updated_at' => '2023-05-05 15:17:50',
            ),
            21 => 
            array (
                'id' => 25,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.4.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 48,
                '_rgt' => 49,
                'parent_id' => 19,
                'created_at' => '2023-05-05 15:17:50',
                'updated_at' => '2023-05-05 15:17:50',
            ),
            22 => 
            array (
                'id' => 26,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.5.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 50,
                '_rgt' => 51,
                'parent_id' => 19,
                'created_at' => '2023-05-05 17:28:56',
                'updated_at' => '2023-05-05 17:28:56',
            ),
            23 => 
            array (
                'id' => 27,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.6.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 52,
                '_rgt' => 53,
                'parent_id' => 19,
                'created_at' => '2023-05-05 19:33:23',
                'updated_at' => '2023-05-05 19:33:23',
            ),
            24 => 
            array (
                'id' => 32,
                'canvas_version_id' => 1,
                'block' => 'custom.video',
                'key' => '',
                'options' => '{"loops": {"loop": {"items": [{}, {}, {}]}}, "color2": "#A8403B", "margin": "py-8 md:py-16 size:large", "padding_top": "pt-8 md:pt-16 top_size:large", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-8 md:pb-16 bottom_size:large", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 55,
                '_rgt' => 66,
                'parent_id' => NULL,
                'created_at' => '2023-05-06 08:56:32',
                'updated_at' => '2023-05-06 08:56:51',
            ),
            25 => 
            array (
                'id' => 33,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<h2><span style=\\"color:#D65A54\\">Persoonlijk</span> in personeel</h2>\\n"}',
                'visible' => 1,
                '_lft' => 56,
                '_rgt' => 57,
                'parent_id' => 32,
                'created_at' => '2023-05-06 08:56:51',
                'updated_at' => '2023-05-06 08:56:51',
            ),
            26 => 
            array (
                'id' => 34,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.0.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 58,
                '_rgt' => 59,
                'parent_id' => 32,
                'created_at' => '2023-05-06 08:56:51',
                'updated_at' => '2023-05-06 08:56:51',
            ),
            27 => 
            array (
                'id' => 35,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.1.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 60,
                '_rgt' => 61,
                'parent_id' => 32,
                'created_at' => '2023-05-06 08:56:51',
                'updated_at' => '2023-05-06 08:56:51',
            ),
            28 => 
            array (
                'id' => 36,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'loop.2.image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 62,
                '_rgt' => 63,
                'parent_id' => 32,
                'created_at' => '2023-05-06 08:56:51',
                'updated_at' => '2023-05-06 08:56:51',
            ),
            29 => 
            array (
                'id' => 37,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.video',
                'key' => 'video',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 64,
                '_rgt' => 65,
                'parent_id' => 32,
                'created_at' => '2023-05-06 08:59:27',
                'updated_at' => '2023-05-06 08:59:27',
            ),
            30 => 
            array (
                'id' => 38,
                'canvas_version_id' => 1,
                'block' => 'canvas::common.2column',
                'key' => '',
                'options' => '{"color": "#A8403B", "margin": "py-8 md:py-16 size:large", "textColor": "white", "padding_top": "pt-8 md:pt-16 top_size:large", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-8 md:pb-16 bottom_size:large", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 67,
                '_rgt' => 72,
                'parent_id' => NULL,
                'created_at' => '2023-05-06 19:20:48',
                'updated_at' => '2023-05-06 19:20:48',
            ),
            31 => 
            array (
                'id' => 39,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'text1',
                'options' => '{"html": "<p><img alt=\\"\\" src=\\"https://hrzeeland-website-galaxy.test/storage/photos/shares/Group_1027.png\\" /></p>\\n\\n<p>Werknemers</p>\\n\\n<h2>Wij geloven in jouw<br />\\npotentieel</h2>\\n\\n<p>Van baan veranderen is niet gemakkelijk, vooral niet als je al een vaste baan hebt. Maar bij de juiste baan en baas krijg je energie en ga je weer elke dag met plezier naar je werk. Bij ons matchen we jou met het juiste bedrijf waarvan we zeker weten dat het bij je past.</p>\\n\\n<p><a class=\\"btn-secondary\\" href=\\"page://4\\">Lees verder</a></p>\\n"}',
                'visible' => 1,
                '_lft' => 68,
                '_rgt' => 69,
                'parent_id' => 38,
                'created_at' => '2023-05-06 19:20:48',
                'updated_at' => '2023-05-06 19:20:48',
            ),
            32 => 
            array (
                'id' => 40,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'text2',
                'options' => '{"html": "<p><img alt=\\"\\" src=\\"https://hrzeeland-website-galaxy.test/storage/photos/shares/Group_1028.png\\" /></p>\\n\\n<p>Werkgevers</p>\\n\\n<h2>Ontdek de kracht van onze persoonlijke HR-aanpak</h2>\\n\\n<p>We adviseren en ondersteunen op het gebied van uitzenden, detacheren, werving &amp; selectie, payrolling, coaching en HR advies. Ons regionale netwerk en onze ervaring maken ons een flexibele en betrouwbare partner. We kunnen snel schakelen en leveren steeds goed en gedegen werk.</p>\\n\\n<p><a class=\\"btn-secondary\\" href=\\"page://3\\">Lees verder</a></p>\\n"}',
                'visible' => 1,
                '_lft' => 70,
                '_rgt' => 71,
                'parent_id' => 38,
                'created_at' => '2023-05-06 19:20:48',
                'updated_at' => '2023-05-06 19:20:48',
            ),
            33 => 
            array (
                'id' => 41,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.button',
                'key' => 'loop.0.button',
                'options' => '{"text": "Accountmanager", "target": "_blank", "linkTarget": "websitePage", "websitePageId": 4, "disableButtonText": "aan"}',
                'visible' => 1,
                '_lft' => 12,
                '_rgt' => 13,
                'parent_id' => 3,
                'created_at' => '2023-05-08 21:37:53',
                'updated_at' => '2023-05-08 21:37:53',
            ),
            34 => 
            array (
                'id' => 42,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.button',
                'key' => 'loop.1.button',
                'options' => '{"text": "Accountmanager"}',
                'visible' => 1,
                '_lft' => 14,
                '_rgt' => 15,
                'parent_id' => 3,
                'created_at' => '2023-05-08 21:37:53',
                'updated_at' => '2023-05-08 21:37:53',
            ),
            35 => 
            array (
                'id' => 43,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.button',
                'key' => 'loop.2.button',
                'options' => '{"text": "Accountmanager"}',
                'visible' => 1,
                '_lft' => 16,
                '_rgt' => 17,
                'parent_id' => 3,
                'created_at' => '2023-05-08 21:37:53',
                'updated_at' => '2023-05-08 21:37:53',
            ),
            36 => 
            array (
                'id' => 44,
                'canvas_version_id' => 1,
                'block' => 'custom.reviews',
                'key' => '',
                'options' => '{"color": "#B54B46", "loops": {"loop": {"items": [{"rating": "75"}, {"rating": "65"}]}}, "margin": "py-8 md:py-16 size:large", "textColor": "white", "padding_top": "pt-12 md:pt-24 top_size:larger", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-12 md:pb-24 bottom_size:larger", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 73,
                '_rgt' => 84,
                'parent_id' => NULL,
                'created_at' => '2023-05-09 03:02:56',
                'updated_at' => '2023-05-09 03:02:56',
            ),
            37 => 
            array (
                'id' => 45,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<h3>Wat onze klanten zeggen</h3>"}',
                'visible' => 1,
                '_lft' => 74,
                '_rgt' => 75,
                'parent_id' => 44,
                'created_at' => '2023-05-09 03:02:56',
                'updated_at' => '2023-05-09 03:02:56',
            ),
            38 => 
            array (
                'id' => 46,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'loop.0.text',
                'options' => '{"html": "<p>Dit is een faketekst. Alles wat hier staat is slechts om een indruk te geven van het grafische effect van tekst op deze plek. Wat u hier leest is een voorbeeldtekst. Deze wordt later vervangen door de uiteindelijke tekst, die nu nog niet bekend is. De faketekst is dus een tekst die eigenlijk nergens over gaat. Het grappige is, dat mensen deze toch vaak lezen. Zelfs als men weet dat het om een faketekst gaat, lezen ze toch door.</p>"}',
                'visible' => 1,
                '_lft' => 76,
                '_rgt' => 77,
                'parent_id' => 44,
                'created_at' => '2023-05-09 03:02:56',
                'updated_at' => '2023-05-09 03:02:56',
            ),
            39 => 
            array (
                'id' => 47,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.line',
                'key' => 'loop.0.line',
                'options' => '{"text": "Auteur"}',
                'visible' => 1,
                '_lft' => 78,
                '_rgt' => 79,
                'parent_id' => 44,
                'created_at' => '2023-05-09 03:02:56',
                'updated_at' => '2023-05-09 03:02:56',
            ),
            40 => 
            array (
                'id' => 48,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'loop.1.text',
                'options' => '{"html": "<p>Dit is een faketekst. Alles wat hier staat is slechts om een indruk te geven van het grafische effect van tekst op deze plek. Wat u hier leest is een voorbeeldtekst. Deze wordt later vervangen door de uiteindelijke tekst, die nu nog niet bekend is. De faketekst is dus een tekst die eigenlijk nergens over gaat. Het grappige is, dat mensen deze toch vaak lezen. Zelfs als men weet dat het om een faketekst gaat, lezen ze toch door.</p>"}',
                'visible' => 1,
                '_lft' => 80,
                '_rgt' => 81,
                'parent_id' => 44,
                'created_at' => '2023-05-09 03:02:56',
                'updated_at' => '2023-05-09 03:02:56',
            ),
            41 => 
            array (
                'id' => 49,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.line',
                'key' => 'loop.1.line',
                'options' => '{"text": "Auteur"}',
                'visible' => 1,
                '_lft' => 82,
                '_rgt' => 83,
                'parent_id' => 44,
                'created_at' => '2023-05-09 03:02:56',
                'updated_at' => '2023-05-09 03:02:56',
            ),
            42 => 
            array (
                'id' => 53,
                'canvas_version_id' => 1,
                'block' => 'custom.leftTextImageRight',
                'key' => '',
                'options' => '{"margin": "py-8 md:py-16 size:large", "padding_top": "pt-12 md:pt-24 top_size:larger", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-12 md:pb-24 bottom_size:larger", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 85,
                '_rgt' => 90,
                'parent_id' => NULL,
                'created_at' => '2023-05-11 09:14:40',
                'updated_at' => '2023-05-11 11:14:44',
            ),
            43 => 
            array (
                'id' => 54,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<h2>Heb je nog vragen of wil je meer informatie?</h2>\\n\\n<p>Aarzel niet om contact met ons op te nemen voor meer informatie<br />\\n&nbsp;</p>\\n\\n<table border=\\"0\\" cellpadding=\\"10\\" cellspacing=\\"1\\" style=\\"width:100%\\">\\n\\t<tbody>\\n\\t\\t<tr>\\n\\t\\t\\t<td><a class=\\"btn-primary\\" href=\\"mailto:info@hrzeeland.nl\\">Stuur een mail</a></td>\\n\\t\\t\\t<td><a class=\\"btn-outline\\" href=\\"#\\">Bel me terug</a></td>\\n\\t\\t</tr>\\n\\t</tbody>\\n</table>\\n"}',
                'visible' => 1,
                '_lft' => 86,
                '_rgt' => 87,
                'parent_id' => 53,
                'created_at' => '2023-05-11 09:14:41',
                'updated_at' => '2023-05-11 11:14:44',
            ),
            44 => 
            array (
                'id' => 55,
                'canvas_version_id' => 1,
                'block' => 'canvas::utils.image',
                'key' => 'image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 88,
                '_rgt' => 89,
                'parent_id' => 53,
                'created_at' => '2023-05-11 09:14:41',
                'updated_at' => '2023-05-11 11:14:44',
            ),
            45 => 
            array (
                'id' => 56,
                'canvas_version_id' => 5,
                'block' => 'canvas::common.leftImageRightTextEqual',
                'key' => '',
                'options' => '{"color": "#D65A54", "margin": "py-8 md:py-16 size:large", "textColor": "white", "padding_top": "pt-8 md:pt-16 top_size:large", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-8 md:pb-16 bottom_size:large", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 1,
                '_rgt' => 6,
                'parent_id' => NULL,
                'created_at' => '2023-05-08 14:02:07',
                'updated_at' => '2023-05-08 14:02:08',
            ),
            46 => 
            array (
                'id' => 57,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.image',
                'key' => 'image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 2,
                '_rgt' => 3,
                'parent_id' => 56,
                'created_at' => '2023-05-08 14:02:08',
                'updated_at' => '2023-05-08 14:02:08',
            ),
            47 => 
            array (
                'id' => 58,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<p>Dit is een faketekst. Alles wat hier staat is slechts om een indruk te geven van het grafische effect van tekst op deze plek. Wat u hier leest is een voorbeeldtekst. Deze wordt later vervangen door de uiteindelijke tekst, die nu nog niet bekend is. De faketekst is dus een tekst die eigenlijk nergens over gaat. Het grappige is, dat mensen deze toch vaak lezen. Zelfs als men weet dat het om een faketekst gaat, lezen ze toch door.</p>"}',
                'visible' => 1,
                '_lft' => 4,
                '_rgt' => 5,
                'parent_id' => 56,
                'created_at' => '2023-05-08 14:02:08',
                'updated_at' => '2023-05-08 14:02:08',
            ),
            48 => 
            array (
                'id' => 63,
                'canvas_version_id' => 5,
                'block' => 'member::modules.members',
                'key' => '',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 25,
                '_rgt' => 28,
                'parent_id' => NULL,
                'created_at' => '2023-05-10 10:15:02',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            49 => 
            array (
                'id' => 64,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<h2>Ons team</h2><p>Leer meer over ons team en ontdek de gezichten die uw ervaring met ons bedrijf persoonlijk en memorabel maken.</p>"}',
                'visible' => 1,
                '_lft' => 26,
                '_rgt' => 27,
                'parent_id' => 63,
                'created_at' => '2023-05-10 10:19:36',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            50 => 
            array (
                'id' => 65,
                'canvas_version_id' => 5,
                'block' => 'custom.5column',
                'key' => '',
                'options' => '{"color": "#FDF2F1", "margin": "py-8 md:py-16 size:large", "padding_top": "pt-8 md:pt-16 top_size:large", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-8 md:pb-16 bottom_size:large", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 29,
                '_rgt' => 40,
                'parent_id' => NULL,
                'created_at' => '2023-05-10 12:36:20',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            51 => 
            array (
                'id' => 66,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text1',
                'options' => '{"html": "<p>Tekst hier</p>"}',
                'visible' => 1,
                '_lft' => 30,
                '_rgt' => 31,
                'parent_id' => 65,
                'created_at' => '2023-05-10 12:36:20',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            52 => 
            array (
                'id' => 67,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text2',
                'options' => '{"html": "<p>Tekst hier</p>"}',
                'visible' => 1,
                '_lft' => 32,
                '_rgt' => 33,
                'parent_id' => 65,
                'created_at' => '2023-05-10 12:36:20',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            53 => 
            array (
                'id' => 68,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text3',
                'options' => '{"html": "<p>Tekst hier</p>"}',
                'visible' => 1,
                '_lft' => 34,
                '_rgt' => 35,
                'parent_id' => 65,
                'created_at' => '2023-05-10 12:36:20',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            54 => 
            array (
                'id' => 69,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text4',
                'options' => '{"html": "<p>Tekst hier</p>"}',
                'visible' => 1,
                '_lft' => 36,
                '_rgt' => 37,
                'parent_id' => 65,
                'created_at' => '2023-05-10 12:36:20',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            55 => 
            array (
                'id' => 70,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text5',
                'options' => '{"html": "<p>Tekst hier</p>"}',
                'visible' => 1,
                '_lft' => 38,
                '_rgt' => 39,
                'parent_id' => 65,
                'created_at' => '2023-05-10 12:36:20',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            56 => 
            array (
                'id' => 71,
                'canvas_version_id' => 5,
                'block' => 'custom.leftTextImageRight',
                'key' => '',
                'options' => '{"margin": "py-8 md:py-16 size:large", "padding_top": "pt-12 md:pt-24 top_size:larger", "padding_left": "left_size:none", "padding_right": "right_size:none", "padding_bottom": "pb-12 md:pb-24 bottom_size:larger", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 41,
                '_rgt' => 46,
                'parent_id' => NULL,
                'created_at' => '2023-05-10 14:36:26',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            57 => 
            array (
                'id' => 72,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<h2>Heb je nog vragen of wil je meer informatie?</h2>\\n\\n<p>Aarzel niet om contact met ons op te nemen voor meer informatie</p>\\n\\n<table border=\\"0\\" cellpadding=\\"10\\" cellspacing=\\"1\\" style=\\"width:100%\\">\\n\\t<tbody>\\n\\t\\t<tr>\\n\\t\\t\\t<td><a class=\\"btn-primary\\" href=\\"mailto:info@hrzeeland.nl\\">Stuur een mail</a></td>\\n\\t\\t\\t<td><a class=\\"btn-outline\\" href=\\"#\\">Bel me terug</a></td>\\n\\t\\t</tr>\\n\\t</tbody>\\n</table>\\n"}',
                'visible' => 1,
                '_lft' => 42,
                '_rgt' => 43,
                'parent_id' => 71,
                'created_at' => '2023-05-10 14:36:26',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            58 => 
            array (
                'id' => 73,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.image',
                'key' => 'image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 44,
                '_rgt' => 45,
                'parent_id' => 71,
                'created_at' => '2023-05-10 14:36:26',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            59 => 
            array (
                'id' => 94,
                'canvas_version_id' => 5,
                'block' => 'custom.2column',
                'key' => '',
                'options' => '{"loops": {"loop": {"items": [{}, {}, {}]}}, "margin": "py-8 md:py-16 size:large", "padding_top": "pt-16 md:pt-32 top_size:extra_large", "padding_left": "horizontal-margin-left-size:medium", "padding_right": "horizontal-margin-right-size:medium", "padding_bottom": "pb-16 md:pb-32 bottom_size:extra_large", "horizontalMargin": "horizontal-margin-size:none"}',
                'visible' => 1,
                '_lft' => 7,
                '_rgt' => 24,
                'parent_id' => NULL,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            60 => 
            array (
                'id' => 95,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.image',
                'key' => 'loop.0.card-icon',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 8,
                '_rgt' => 9,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            61 => 
            array (
                'id' => 96,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.line',
                'key' => 'loop.0.title',
                'options' => '{"text": "Techniek"}',
                'visible' => 1,
                '_lft' => 10,
                '_rgt' => 11,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            62 => 
            array (
                'id' => 97,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.image',
                'key' => 'loop.1.card-icon',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 12,
                '_rgt' => 13,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            63 => 
            array (
                'id' => 98,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.line',
                'key' => 'loop.1.title',
                'options' => '{"text": "Techniek"}',
                'visible' => 1,
                '_lft' => 14,
                '_rgt' => 15,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            64 => 
            array (
                'id' => 99,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.image',
                'key' => 'loop.2.card-icon',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 16,
                '_rgt' => 17,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            65 => 
            array (
                'id' => 100,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.line',
                'key' => 'loop.2.title',
                'options' => '{"text": "Techniek"}',
                'visible' => 1,
                '_lft' => 18,
                '_rgt' => 19,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            66 => 
            array (
                'id' => 101,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.text',
                'key' => 'text',
                'options' => '{"html": "<p><span style=\\"color:#ffffff\\">Detacheren</span><br />\\n&nbsp;</p>\\n\\n<p><span style=\\"color:#ffffff\\">Werving &amp; Selectie</span><br />\\n&nbsp;</p>\\n\\n<p><span style=\\"color:#ffffff\\">Uitzenden</span><br />\\n&nbsp;</p>\\n\\n<p><span style=\\"color:#ffffff\\">HR Interim</span><br />\\n&nbsp;</p>\\n\\n<p><span style=\\"color:#ffffff\\">Jobcoaching</span><br />\\n&nbsp;</p>\\n\\n<p><span style=\\"color:#ffffff\\">Payrolling</span></p>\\n"}',
                'visible' => 1,
                '_lft' => 20,
                '_rgt' => 21,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
            67 => 
            array (
                'id' => 102,
                'canvas_version_id' => 5,
                'block' => 'canvas::utils.image',
                'key' => 'image',
                'options' => '{}',
                'visible' => 1,
                '_lft' => 22,
                '_rgt' => 23,
                'parent_id' => 94,
                'created_at' => '2023-05-11 03:26:04',
                'updated_at' => '2023-05-11 05:26:19',
            ),
        ));
        
        
    }
}