<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class WebsitePagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('website_pages')->delete();
        
        \DB::table('website_pages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'website_id' => 1,
                'canvas_id' => 1,
                'slug' => '{"nl": ""}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Home"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[{"__dataset_item_id":"0","image":5,"title":{"nl":"Lokale kennis, persoonlijke service"},"description":{"nl":"Zeeuwse partner voor het vinden van werk en werknemers"},"websitePageOrLink":"1","websitepage":"3","link":null,"websitepage_text":{"nl":"Bekijk de vacatures"}}]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-08 16:04:11',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => 1,
                'output_options' => NULL,
                'created_at' => '2023-05-08 11:07:39',
                'updated_at' => '2023-05-11 15:15:55',
                'is_group' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'website_id' => 1,
                'canvas_id' => 5,
                'slug' => '{"nl": "wie-zijn-wij"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Wie zijn wij"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[{"__dataset_item_id":"0","image":28,"title":{"nl":"Lokale kennis, persoonlijke service"},"description":{"nl":"Zeeuwse partner voor het vinden van werk en werknemers"},"websitePageOrLink":"1","websitepage":"2","link":null,"websitepage_text":{"nl":"Bekijk de vacatures"}}]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-11 16:11:21',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2023-05-08 12:21:53',
                'updated_at' => '2023-05-12 11:39:04',
                'is_group' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'website_id' => 1,
                'canvas_id' => 6,
                'slug' => '{"nl": "werkgevers"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Werkgevers"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-11 11:18:04',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2023-05-08 12:21:59',
                'updated_at' => '2023-05-11 11:18:04',
                'is_group' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'website_id' => 1,
                'canvas_id' => 7,
                'slug' => '{"nl": "werknemers"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Werknemers"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-11 11:18:09',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2023-05-08 12:22:03',
                'updated_at' => '2023-05-11 11:18:09',
                'is_group' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'website_id' => 1,
                'canvas_id' => 8,
                'slug' => '{"nl": "reviews"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Reviews"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-11 11:18:13',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2023-05-08 12:22:08',
                'updated_at' => '2023-05-11 11:18:13',
                'is_group' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'website_id' => 1,
                'canvas_id' => 9,
                'slug' => '{"nl": "contact"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Contact"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-11 11:18:16',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2023-05-08 12:22:13',
                'updated_at' => '2023-05-11 11:18:16',
                'is_group' => 0,
            ),
            6 => 
            array (
                'id' => 8,
                'website_id' => 1,
                'canvas_id' => 11,
                'slug' => '{"nl": "algemene-voorwaarden"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Algemene voorwaarden"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-11 13:21:24',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2023-05-11 13:21:24',
                'updated_at' => '2023-05-11 13:21:24',
                'is_group' => 0,
            ),
            7 => 
            array (
                'id' => 9,
                'website_id' => 1,
                'canvas_id' => 12,
                'slug' => '{"nl": "privacy-policy"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Privacy Policy"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => '[]',
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => NULL,
                'module_options' => NULL,
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2023-05-11 13:21:29',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2023-05-11 13:21:29',
                'updated_at' => '2023-05-11 13:21:29',
                'is_group' => 0,
            ),
            8 => 
            array (
                'id' => 10,
                'website_id' => 1,
                'canvas_id' => NULL,
                'slug' => '{"nl": "vacatures"}',
                'redirect' => '{"nl": null}',
                'title_page' => '{"nl": "Vacatures"}',
                'title_menu' => '{"nl": null}',
                'meta_description' => '{"nl": null}',
                'robot_index' => 1,
                'slider' => NULL,
                'search_index' => 1,
                'is_megamenu' => 0,
                'show_slider' => 1,
                'cache_disabled' => 0,
                'module_id' => 'vacancy::vacancy',
                'module_options' => '{"vacancy_amount": "10"}',
                'design_style' => NULL,
                'last_edited_user_id' => 1,
                'last_edited_at' => '2024-10-29 11:01:36',
                'published' => 1,
                'publish_at' => NULL,
                'unpublish_at' => NULL,
                'is_deletable' => 1,
                'target_blank' => 0,
                'is_fancy_redirect' => 0,
                'is_homepage' => NULL,
                'output_options' => NULL,
                'created_at' => '2024-10-29 11:01:37',
                'updated_at' => '2024-10-29 11:01:40',
                'is_group' => 0,
            ),
        ));
        
        
    }
}